{
 "title": "croit - Main Dashboard",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "5m",
 "panels": [
  { "title": "Cluster stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "IOPS",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "target": "alias(croit-ceph-mons.ceph.disk_ops-total.read, 'Read')"
    },
    {
     "target": "alias(croit-ceph-mons.ceph.disk_ops-total.write, 'Write')"
    }
   ]
  },
  {
   "title": "Bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "target": "alias(croit-ceph-mons.ceph.disk_octets-total.read, 'Read')"
    },
    {
     "target": "alias(croit-ceph-mons.ceph.disk_octets-total.write, 'Write')"
    }
   ]
  },
  {
   "title": "Operation Latency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "target": "alias(percentileOfSeries(croit-ceph-mons.ceph-osd-*-op_latency.latency, 99), '99. Percentile')"
    },
    {
     "target": "alias(percentileOfSeries(croit-ceph-mons.ceph-osd-*-op_latency.latency, 90), '90. Percentile')"
    },
    {
     "target": "alias(percentileOfSeries(croit-ceph-mons.ceph-osd-*-op_latency.latency, 50), '50. Percentile')"
    }
   ]
  },
  {
   "title": "Recovery",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "target": "alias(croit-ceph-mons.ceph.bytes-recovery, 'Bytes')"
    },
    {
     "target": "alias(croit-ceph-mons.ceph.objects-recovery, 'Objects')"
    }
   ]
  },
  {
   "title": "PG State",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "target": "aliasSub(exclude(exclude(croit-ceph-mons.ceph.gauge-pgs-*, '.*active$'), '.*clean$'), \".+\\pgs-(\\w+)\", \"\\1\")"
    }
   ]
  },
  {
   "title": "OSD State",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "target": "alias(diffSeries(croit-ceph-mons.ceph.gauge-osds, croit-ceph-mons.ceph.gauge-osds-in), \"Out\")"
    },
    {
     "target": "alias(diffSeries(croit-ceph-mons.ceph.gauge-osds, croit-ceph-mons.ceph.gauge-osds-up), \"Down\")"
    }
   ]
  },
  { "title": "Server stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Data Balance",
   "type": "timeseries",
   "gridPos": { "h": 22, "w": 8, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "target": "aliasSub(exclude(exclude(exclude(exclude(exclude(croit-server-*.df-*.percent_bytes-used, 'cephfs'), 'var-lib-ceph-mon'), 'squashfs'), 'root'), 'tmp-mnt'), '.*ceph\\-osd\\-ceph\\-(\\d*).*', 'OSD \\1 Disk Usage')"
    }
   ]
  },
  {
   "title": "IO Load",
   "type": "table",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "target": "aliasSub(scale(removeAboveValue(averageSeriesWithWildcards(croit-server-*.disk-*.disk_io_time.io_time, 1), 1010), 0.1), 'scale\\(removeAboveValue\\(croit-server-([^.]*)\\.disk.*', 'Server \\1')"
    }
   ]
  },
  {
   "title": "CPU Load",
   "type": "table",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "target": "aliasSub(averageSeriesWithWildcards(croit-server-*.cpu-*.percent-active, 1), 'croit-server-([^.]*)\\.percent.*', 'Server \\1')"
    }
   ]
  }
 ]
}