{
 "title": "croit - Per-Pool Stats",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "Pool",
    "query": "croit-ceph-mons.ceph.bytes-pool-*"
   },
   { "name": "Smoothing", "query": "10s,1min,10min,1h,24h" }
  ]
 },
 "panels": [
  { "title": "New row", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Disk Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "target": "alias(sum(croit-ceph-mons.ceph.bytes-pool-$Pool), 'Bytes used')"
    },
    {
     "target": "alias(sum(croit-ceph-mons.ceph.objects-pool-$Pool), 'Objects')"
    }
   ]
  },
  { "title": "Pool: $Pool", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 }, "repeat": "Pool" },
  {
   "title": "IOPS",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "target": "alias(movingAverage(croit-ceph-mons.ceph.disk_ops-pool-$Pool.read, '$Smoothing'), 'Read')"
    },
    {
     "target": "alias(movingAverage(croit-ceph-mons.ceph.disk_ops-pool-$Pool.write, '$Smoothing'), 'Write')"
    }
   ]
  },
  {
   "title": "Bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "target": "alias(movingAverage(croit-ceph-mons.ceph.disk_octets-pool-$Pool.read, '$Smoothing'), 'Read')"
    },
    {
     "target": "alias(movingAverage(croit-ceph-mons.ceph.disk_octets-pool-$Pool.write, '$Smoothing'), 'Write')"
    }
   ]
  },
  {
   "title": "Disk Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "target": "alias(croit-ceph-mons.ceph.bytes-pool-$Pool, 'Bytes used')"
    },
    {
     "target": "alias(croit-ceph-mons.ceph.objects-pool-$Pool, 'Objects used')"
    }
   ]
  }
 ]
}