{
 "title": "croit - Latency Overview",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Op Latency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "target": "alias(percentileOfSeries(croit-ceph-mons.ceph-osd-*-op_latency.latency, 99), '99. Percentile')"
    },
    {
     "target": "alias(percentileOfSeries(croit-ceph-mons.ceph-osd-*-op_latency.latency, 90), '90. Percentile')"
    },
    {
     "target": "alias(percentileOfSeries(croit-ceph-mons.ceph-osd-*-op_latency.latency, 50), '50. Percentile')"
    }
   ]
  },
  {
   "title": "Subop Latency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "target": "alias(percentileOfSeries(croit-ceph-mons.ceph-osd-*-subop_latency.latency, 99), '99. Percentile')"
    },
    {
     "target": "alias(percentileOfSeries(croit-ceph-mons.ceph-osd-*-subop_latency.latency, 90), '90. Percentile')"
    },
    {
     "target": "alias(percentileOfSeries(croit-ceph-mons.ceph-osd-*-subop_latency.latency, 50), '50. Percentile')"
    }
   ]
  },
  {
   "title": "Write Op Latency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "target": "alias(percentileOfSeries(croit-ceph-mons.ceph-osd-*-op_w_latency.latency, 99), '99. Percentile')"
    },
    {
     "target": "alias(percentileOfSeries(croit-ceph-mons.ceph-osd-*-op_w_latency.latency, 90), '90. Percentile')"
    },
    {
     "target": "alias(percentileOfSeries(croit-ceph-mons.ceph-osd-*-op_w_latency.latency, 50), '50. Percentile')"
    }
   ]
  },
  {
   "title": "Read Op Latency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "target": "alias(percentileOfSeries(croit-ceph-mons.ceph-osd-*-op_r_latency.latency, 99), '99. Percentile')"
    },
    {
     "target": "alias(percentileOfSeries(croit-ceph-mons.ceph-osd-*-op_r_latency.latency, 90), '90. Percentile')"
    },
    {
     "target": "alias(percentileOfSeries(croit-ceph-mons.ceph-osd-*-op_r_latency.latency, 50), '50. Percentile')"
    }
   ]
  }
 ]
}