{
 "title": "croit - CPU Overview",
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   { "name": "Server", "query": "croit-server-*" },
   { "name": "Smoothing", "label": "Smoothing", "query": "10s,30s,1m,10m,1h" }
  ]
 },
 "panels": [
  { "title": "$Server", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "Server" },
  {
   "title": "CPU Load",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "target": "aliasSub(movingAverage(croit-$Server.cpu-*.percent-active, '$Smoothing'), 'movingAverage\\(croit-server-.*cpu-(.*)\\..*', 'Core \\1')"
    }
   ]
  },
  {
   "title": "System Load",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "target": "alias(movingAverage(croit-$Server.load.load.shortterm, '$Smoothing'), 'Load average (1 min)')"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "target": "alias(movingAverage(croit-$Server.memory.memory-used, '$Smoothing'), 'Memory used')\""
    },
    {
     "target": "alias(movingAverage(croit-$Server.memory.memory-buffered, '$Smoothing'), 'Buffers')\""
    },
    {
     "target": "alias(movingAverage(sumSeries(croit-$Server.memory.{memory-buffered,memory-cached,memory-free}), '$Smoothing'), 'Memory free')"
    }
   ]
  }
 ]
}